global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'api-gateway'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'api-gateway:7000' ]

- job_name: 'book-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'book-service:7004' ]

- job_name: 'user-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'user-service:7005' ]

- job_name: 'loan-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'loan-service:7006' ]

# Jika menggunakan Node Exporter untuk host metrics
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
